java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation project(':common')
    implementation project(':domain:jpa-common')
    implementation project(':domain:jpa-member-domain')

    implementation('org.springframework.boot:spring-boot-starter-test')
}