spring:
  application:
    name: wypl-calendar
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: true
      path: /h2

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2