spring:
  application:
    name: wypl-core
  config:
    import:
      - security/application-mongo.yml
      - security/application-oracle.yml
      - security/application-weather.yml
    activate:
      on-profile:
        - default
        - local
        - dev
        - prod