spring:
  application:
    name: wypl-image
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true

cloud:
  aws:
    s3:
      bucket: cloud-aws-s3-bucket
    credentials:
      access-key: cloud-aws-s3-credentials-access-key
      secret-key: cloud-aws-s3-credentials-secret-key

working:
  directory:
    absolute-path: magick

---

spring:
  config:
    import:
      - security/application-aws.yml
      - security/application-disk.yml
    activate:
      on-profile:
        - dev
        - prod
