java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation project(':domain:jpa-common')
    implementation project(':common')

    /* QueryDSL */
    implementation('com.querydsl:querydsl-jpa:5.0.0:jakarta')
    annotationProcessor('com.querydsl:querydsl-apt:5.0.0:jakarta')
    annotationProcessor('jakarta.annotation:jakarta.annotation-api')
    annotationProcessor('jakarta.persistence:jakarta.persistence-api')
}


/ QueryDSL Start /
def generated = "src/main/generated"

tasks.withType(JavaCompile).configureEach {
    options.getGeneratedSourceOutputDirectory().set(file(generated))
}

sourceSets {
    main.java.srcDirs += [generated]
}

clean {
    delete file(generated)
}
/ QueryDSL End */