name: 🧪 Image Server Tests on Pull Request

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  project-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🖼️ Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: 🏗️ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🎟️ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🧪 Spring Boot Test
        run: ./gradlew clean application:wypl-image:test

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📄 Jacoco Coverage Report
          paths: ${{ github.workspace }}/**/wypl-image/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80